### ISSUE TITLE
[Bug]: Qwen3-Next-80B-A3B-Instruct-int4-mixed-AutoRound vLLM inference failed

### ISSUE THREAD

**Issue by chensuyue** [intel/auto-round#1499]
### Problem Description

Released model Qwen3-Next-80B-A3B-Instruct-int4-mixed-AutoRound vLLM inference failed. 


### Reproduction Steps

```shell
export CUDA_VISIBLE_DEVICES=3,4,5,6
export NCCL_NVLS_ENABLE=0
export VLLM_ALLREDUCE_USE_SYMM_MEM=0
export VLLM_USE_NCCL_SYMM_MEM=0
vllm serve Intel/Qwen3-Next-80B-A3B-Instruct-int4-mixed-AutoRound --served-model-name Qwen3-Next  --tensor-parallel-size 4 --max-num-seqs 8 --gpu-memory-utilization 0.9 --dtype float16 --enable-expert-parallel
```

### Environment Information

- vLLM: v0.16.0  
- HW: B200, 4 cards 

### Error Logs

```shell
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]   File "/usr/local/lib/python3.12/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 353, in runtime_wrapper                         
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]     all_outs = call_func_at_runtime_with_args(                                                                                                            
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                            
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]   File "/usr/local/lib/python3.12/dist-packages/torch/_functorch/_aot_autograd/utils.py", line 129, in call_func_at_runtime_with_args                     
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]     out = normalize_as_list(f(args))                                                                                                                      
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]                             ^^^^^^^                                                                                                                       
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]   File "/usr/local/lib/python3.12/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 526, in wrapper                                 
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]     return compiled_fn(runtime_args)                                                                                                                      
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]            ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                      
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]   File "/usr/local/lib/python3.12/dist-packages/torch/_inductor/output_code.py", line 613, in __call__                                                    
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]     return self.current_callable(inputs)                                                                                                                  
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                  
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]   File "/usr/local/lib/python3.12/dist-packages/torch/_inductor/utils.py", line 3017, in run                                                              
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]     out = model(new_inputs)                                                                                                                               
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]           ^^^^^^^^^^^^^^^^^                                                                                                                               
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]   File "/tmp/torchinductor_root/yn/cyn6oi36lhs2wrqx7q4ydnlsftadkn3d4yvpqoepqn6y3exzllur.py", line 1372, in call                                           
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]     buf2 = torch.ops._C.marlin_gemm.default(buf1, None, arg4_1, None, arg5_1, None, None, arg6_1, arg7_1, arg8_1, arg9_1, 1125899923621888, s72, 2048, 102
4, True, False, True, False)                                                                                                                                                                                                          
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                          
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]   File "/usr/local/lib/python3.12/dist-packages/torch/_ops.py", line 841, in __call__                                                                     
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]     return self._op(*args, **kwargs)                                                                                                                      
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863]            ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                      
(Worker_TP2_EP2 pid=45072) ERROR 03-04 13:59:50 [multiproc_executor.py:863] RuntimeError: unsupported `a` scalar_type
```

### Additional Context

_No response_

**Comment by chensuyue** [comment]
Refresh the quantized model, @XuehaoSun

**Comment by XuehaoSun** [comment]
```
vllm serve /data0/saved/Qwen3-Next-80B-A3B-Instruct-int4-mixed/Qwen3-Next-80B-A3B-Instruct-w4g128 --port 7777 --host localhost --trust-remote-code --dtype bfloat16 --tensor_parallel_size 2 --max-model-len 4096 --max-num-seqs 16 --gpu-memory-utilization 0.8
```
```
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852] WorkerProc failed to start.
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852] Traceback (most recent call last):
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]   File "/home/uttest/miniforge3/envs/vllm/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 821, in worker_main
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]     worker = WorkerProc(*args, **kwargs)
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]   File "/home/uttest/miniforge3/envs/vllm/lib/python3.12/site-packages/vllm/tracing/otel.py", line 178, in sync_wrapper
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]     return func(*args, **kwargs)
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]            ^^^^^^^^^^^^^^^^^^^^^
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]   File "/home/uttest/miniforge3/envs/vllm/lib/python3.12/site-packages/vllm/v1/executor/multiproc_executor.py", line 619, in __init__
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]     self.worker.load_model()
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]   File "/home/uttest/miniforge3/envs/vllm/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 335, in load_model
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]     self.model_runner.load_model(load_dummy_weights=dummy_weights)
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]   File "/home/uttest/miniforge3/envs/vllm/lib/python3.12/site-packages/vllm/tracing/otel.py", line 178, in sync_wrapper
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]     return func(*args, **kwargs)
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]            ^^^^^^^^^^^^^^^^^^^^^
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]   File "/home/uttest/miniforge3/envs/vllm/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 4497, in load_model
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]     self.model = model_loader.load_model(
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]                  ^^^^^^^^^^^^^^^^^^^^^^^^
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]   File "/home/uttest/miniforge3/envs/vllm/lib/python3.12/site-packages/vllm/tracing/otel.py", line 178, in sync_wrapper
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]     return func(*args, **kwargs)
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]            ^^^^^^^^^^^^^^^^^^^^^
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]   File "/home/uttest/miniforge3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/model_loader/base_loader.py", line 62, in load_model
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]     self.load_weights(model, model_config)
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]   File "/home/uttest/miniforge3/envs/vllm/lib/python3.12/site-packages/vllm/tracing/otel.py", line 178, in sync_wrapper
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]     return func(*args, **kwargs)
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]            ^^^^^^^^^^^^^^^^^^^^^
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]   File "/home/uttest/miniforge3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/model_loader/default_loader.py", line 381, in load_weights
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]     loaded_weights = model.load_weights(self.get_all_weights(model_config, model))
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]   File "/home/uttest/miniforge3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/models/qwen3_next.py", line 1667, in load_weights
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]     return loader.load_weights(weights)
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]   File "/home/uttest/miniforge3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/model_loader/reload/torchao_decorator.py", line 50, in patched_model_load_weights
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]     return original_load_weights(self, weights, *args, **kwargs)
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]   File "/home/uttest/miniforge3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/models/utils.py", line 348, in load_weights
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]     autoloaded_weights = set(self._load_module("", self.module, weights))
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]   File "/home/uttest/miniforge3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/models/utils.py", line 295, in _load_module
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]     yield from self._load_module(
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]   File "/home/uttest/miniforge3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/models/utils.py", line 268, in _load_module
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]     loaded_params = module_load_weights(weights)
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]   File "/home/uttest/miniforge3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/models/qwen3_next.py", line 1457, in load_weights
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]     weight_loader(param, loaded_weight, shard_id)
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]   File "/home/uttest/miniforge3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/layers/linear.py", line 942, in weight_loader_v2
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]     param.load_merged_column_weight(
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]   File "/home/uttest/miniforge3/envs/vllm/lib/python3.12/site-packages/vllm/model_executor/parameter.py", line 175, in load_merged_column_weight
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]     assert param_data.shape == loaded_weight.shape
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[VLLM LOG] (Worker_TP1 pid=1616714) ERROR 04-13 13:20:01 [multiproc_executor.py:852] AssertionError
```

**Comment by yiliu30** [comment]
Hi @XuehaoSun, I have fixed the configuration issue in this quantized model. Please verify it with TP 1.

```
vllm serve /data0/saved/Qwen3-Next-80B-A3B-Instruct-int4-mixed/Qwen3-Next-80B-A3B-Instruct-w4g128 --port 7777 --host localhost --trust-remote-code --dtype bfloat16 --tensor_parallel_size 1 --max-model-len 4096 --max-num-seqs 16 --gpu-memory-utilization 0.8
```

<img width="422" height="193" alt="Image" src="https://github.com/user-attachments/assets/fd529c0d-7a80-4819-ac88-8f44ffb1d2ff" />

Also note, we can get the right quantized model w/ `AR_DISABLE_COPY_MTP_WEIGHTS=1`.

cc @xin3he

**Comment by yiliu30** [comment]
Reopen it until the fix PR is merged.
